./gradlew :kuberig-dsl-kubernetes-v1.10.7:build :kuberig-dsl-kubernetes-v1.10.7:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.10.8:build :kuberig-dsl-kubernetes-v1.10.8:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.10.8-beta.0:build :kuberig-dsl-kubernetes-v1.10.8-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.10.9:build :kuberig-dsl-kubernetes-v1.10.9:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.10.9-beta.0:build :kuberig-dsl-kubernetes-v1.10.9-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.10.10:build :kuberig-dsl-kubernetes-v1.10.10:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.10.10-beta.0:build :kuberig-dsl-kubernetes-v1.10.10-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.10.11:build :kuberig-dsl-kubernetes-v1.10.11:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.10.11-beta.0:build :kuberig-dsl-kubernetes-v1.10.11-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.10.12:build :kuberig-dsl-kubernetes-v1.10.12:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.10.12-beta.0:build :kuberig-dsl-kubernetes-v1.10.12-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.10.13:build :kuberig-dsl-kubernetes-v1.10.13:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.10.13-beta.0:build :kuberig-dsl-kubernetes-v1.10.13-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.10.14-beta.0:build :kuberig-dsl-kubernetes-v1.10.14-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.0:build :kuberig-dsl-kubernetes-v1.11.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.0-alpha.0:build :kuberig-dsl-kubernetes-v1.11.0-alpha.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.0-alpha.1:build :kuberig-dsl-kubernetes-v1.11.0-alpha.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.0-alpha.2:build :kuberig-dsl-kubernetes-v1.11.0-alpha.2:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.0-beta.0:build :kuberig-dsl-kubernetes-v1.11.0-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.0-beta.1:build :kuberig-dsl-kubernetes-v1.11.0-beta.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.0-beta.2:build :kuberig-dsl-kubernetes-v1.11.0-beta.2:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.0-rc.1:build :kuberig-dsl-kubernetes-v1.11.0-rc.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.0-rc.2:build :kuberig-dsl-kubernetes-v1.11.0-rc.2:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.0-rc.3:build :kuberig-dsl-kubernetes-v1.11.0-rc.3:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.1:build :kuberig-dsl-kubernetes-v1.11.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.1-beta.0:build :kuberig-dsl-kubernetes-v1.11.1-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.2:build :kuberig-dsl-kubernetes-v1.11.2:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.2-beta.0:build :kuberig-dsl-kubernetes-v1.11.2-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.3:build :kuberig-dsl-kubernetes-v1.11.3:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.3-beta.0:build :kuberig-dsl-kubernetes-v1.11.3-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.4:build :kuberig-dsl-kubernetes-v1.11.4:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.4-beta.0:build :kuberig-dsl-kubernetes-v1.11.4-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.5:build :kuberig-dsl-kubernetes-v1.11.5:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.5-beta.0:build :kuberig-dsl-kubernetes-v1.11.5-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.6:build :kuberig-dsl-kubernetes-v1.11.6:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.6-beta.0:build :kuberig-dsl-kubernetes-v1.11.6-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.7:build :kuberig-dsl-kubernetes-v1.11.7:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.7-beta.0:build :kuberig-dsl-kubernetes-v1.11.7-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.8:build :kuberig-dsl-kubernetes-v1.11.8:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.8-beta.0:build :kuberig-dsl-kubernetes-v1.11.8-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.9:build :kuberig-dsl-kubernetes-v1.11.9:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.9-beta.0:build :kuberig-dsl-kubernetes-v1.11.9-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.10:build :kuberig-dsl-kubernetes-v1.11.10:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.10-beta.0:build :kuberig-dsl-kubernetes-v1.11.10-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.11.11-beta.0:build :kuberig-dsl-kubernetes-v1.11.11-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.0:build :kuberig-dsl-kubernetes-v1.12.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.0-alpha.0:build :kuberig-dsl-kubernetes-v1.12.0-alpha.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.0-alpha.1:build :kuberig-dsl-kubernetes-v1.12.0-alpha.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.0-beta.0:build :kuberig-dsl-kubernetes-v1.12.0-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.0-beta.1:build :kuberig-dsl-kubernetes-v1.12.0-beta.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.0-beta.2:build :kuberig-dsl-kubernetes-v1.12.0-beta.2:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.0-rc.1:build :kuberig-dsl-kubernetes-v1.12.0-rc.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.0-rc.2:build :kuberig-dsl-kubernetes-v1.12.0-rc.2:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.1:build :kuberig-dsl-kubernetes-v1.12.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.1-beta.0:build :kuberig-dsl-kubernetes-v1.12.1-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.2:build :kuberig-dsl-kubernetes-v1.12.2:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.2-beta.0:build :kuberig-dsl-kubernetes-v1.12.2-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.3:build :kuberig-dsl-kubernetes-v1.12.3:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.3-beta.0:build :kuberig-dsl-kubernetes-v1.12.3-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.4:build :kuberig-dsl-kubernetes-v1.12.4:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.4-beta.0:build :kuberig-dsl-kubernetes-v1.12.4-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.5:build :kuberig-dsl-kubernetes-v1.12.5:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.5-beta.0:build :kuberig-dsl-kubernetes-v1.12.5-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.6:build :kuberig-dsl-kubernetes-v1.12.6:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.6-beta.0:build :kuberig-dsl-kubernetes-v1.12.6-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.7:build :kuberig-dsl-kubernetes-v1.12.7:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.7-beta.0:build :kuberig-dsl-kubernetes-v1.12.7-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.8:build :kuberig-dsl-kubernetes-v1.12.8:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.8-beta.0:build :kuberig-dsl-kubernetes-v1.12.8-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.9:build :kuberig-dsl-kubernetes-v1.12.9:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.9-beta.0:build :kuberig-dsl-kubernetes-v1.12.9-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.10:build :kuberig-dsl-kubernetes-v1.12.10:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.10-beta.0:build :kuberig-dsl-kubernetes-v1.12.10-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.12.11-beta.0:build :kuberig-dsl-kubernetes-v1.12.11-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.0:build :kuberig-dsl-kubernetes-v1.13.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.0-alpha.0:build :kuberig-dsl-kubernetes-v1.13.0-alpha.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.0-alpha.1:build :kuberig-dsl-kubernetes-v1.13.0-alpha.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.0-alpha.2:build :kuberig-dsl-kubernetes-v1.13.0-alpha.2:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.0-alpha.3:build :kuberig-dsl-kubernetes-v1.13.0-alpha.3:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.0-beta.0:build :kuberig-dsl-kubernetes-v1.13.0-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.0-beta.1:build :kuberig-dsl-kubernetes-v1.13.0-beta.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.0-beta.2:build :kuberig-dsl-kubernetes-v1.13.0-beta.2:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.0-rc.1:build :kuberig-dsl-kubernetes-v1.13.0-rc.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.0-rc.2:build :kuberig-dsl-kubernetes-v1.13.0-rc.2:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.1:build :kuberig-dsl-kubernetes-v1.13.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.1-beta.0:build :kuberig-dsl-kubernetes-v1.13.1-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.2:build :kuberig-dsl-kubernetes-v1.13.2:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.2-beta.0:build :kuberig-dsl-kubernetes-v1.13.2-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.3:build :kuberig-dsl-kubernetes-v1.13.3:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.3-beta.0:build :kuberig-dsl-kubernetes-v1.13.3-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.4:build :kuberig-dsl-kubernetes-v1.13.4:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.4-beta.0:build :kuberig-dsl-kubernetes-v1.13.4-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.5:build :kuberig-dsl-kubernetes-v1.13.5:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.5-beta.0:build :kuberig-dsl-kubernetes-v1.13.5-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.6:build :kuberig-dsl-kubernetes-v1.13.6:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.6-beta.0:build :kuberig-dsl-kubernetes-v1.13.6-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.7:build :kuberig-dsl-kubernetes-v1.13.7:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.7-beta.0:build :kuberig-dsl-kubernetes-v1.13.7-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.8:build :kuberig-dsl-kubernetes-v1.13.8:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.8-beta.0:build :kuberig-dsl-kubernetes-v1.13.8-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.9:build :kuberig-dsl-kubernetes-v1.13.9:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.9-beta.0:build :kuberig-dsl-kubernetes-v1.13.9-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.10:build :kuberig-dsl-kubernetes-v1.13.10:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.10-beta.0:build :kuberig-dsl-kubernetes-v1.13.10-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.11:build :kuberig-dsl-kubernetes-v1.13.11:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.11-beta.0:build :kuberig-dsl-kubernetes-v1.13.11-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.12:build :kuberig-dsl-kubernetes-v1.13.12:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.12-beta.0:build :kuberig-dsl-kubernetes-v1.13.12-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.13.13-beta.0:build :kuberig-dsl-kubernetes-v1.13.13-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.0:build :kuberig-dsl-kubernetes-v1.14.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.0-alpha.0:build :kuberig-dsl-kubernetes-v1.14.0-alpha.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.0-alpha.1:build :kuberig-dsl-kubernetes-v1.14.0-alpha.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.0-alpha.2:build :kuberig-dsl-kubernetes-v1.14.0-alpha.2:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.0-alpha.3:build :kuberig-dsl-kubernetes-v1.14.0-alpha.3:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.0-beta.0:build :kuberig-dsl-kubernetes-v1.14.0-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.0-beta.1:build :kuberig-dsl-kubernetes-v1.14.0-beta.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.0-beta.2:build :kuberig-dsl-kubernetes-v1.14.0-beta.2:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.0-rc.1:build :kuberig-dsl-kubernetes-v1.14.0-rc.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.1:build :kuberig-dsl-kubernetes-v1.14.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.1-beta.0:build :kuberig-dsl-kubernetes-v1.14.1-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.2:build :kuberig-dsl-kubernetes-v1.14.2:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.2-beta.0:build :kuberig-dsl-kubernetes-v1.14.2-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.3:build :kuberig-dsl-kubernetes-v1.14.3:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.3-beta.0:build :kuberig-dsl-kubernetes-v1.14.3-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.4:build :kuberig-dsl-kubernetes-v1.14.4:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.4-beta.0:build :kuberig-dsl-kubernetes-v1.14.4-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.5:build :kuberig-dsl-kubernetes-v1.14.5:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.5-beta.0:build :kuberig-dsl-kubernetes-v1.14.5-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.6:build :kuberig-dsl-kubernetes-v1.14.6:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.6-beta.0:build :kuberig-dsl-kubernetes-v1.14.6-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.7:build :kuberig-dsl-kubernetes-v1.14.7:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.7-beta.0:build :kuberig-dsl-kubernetes-v1.14.7-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.8:build :kuberig-dsl-kubernetes-v1.14.8:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.8-beta.0:build :kuberig-dsl-kubernetes-v1.14.8-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.9:build :kuberig-dsl-kubernetes-v1.14.9:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.9-beta.0:build :kuberig-dsl-kubernetes-v1.14.9-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.10:build :kuberig-dsl-kubernetes-v1.14.10:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.10-beta.0:build :kuberig-dsl-kubernetes-v1.14.10-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.11-beta.0:build :kuberig-dsl-kubernetes-v1.14.11-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.14.11-beta.1:build :kuberig-dsl-kubernetes-v1.14.11-beta.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.0:build :kuberig-dsl-kubernetes-v1.15.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.0-alpha.0:build :kuberig-dsl-kubernetes-v1.15.0-alpha.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.0-alpha.1:build :kuberig-dsl-kubernetes-v1.15.0-alpha.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.0-alpha.2:build :kuberig-dsl-kubernetes-v1.15.0-alpha.2:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.0-alpha.3:build :kuberig-dsl-kubernetes-v1.15.0-alpha.3:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.0-beta.0:build :kuberig-dsl-kubernetes-v1.15.0-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.0-beta.1:build :kuberig-dsl-kubernetes-v1.15.0-beta.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.0-beta.2:build :kuberig-dsl-kubernetes-v1.15.0-beta.2:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.0-rc.1:build :kuberig-dsl-kubernetes-v1.15.0-rc.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.1:build :kuberig-dsl-kubernetes-v1.15.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.1-beta.0:build :kuberig-dsl-kubernetes-v1.15.1-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.2:build :kuberig-dsl-kubernetes-v1.15.2:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.2-beta.0:build :kuberig-dsl-kubernetes-v1.15.2-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.3:build :kuberig-dsl-kubernetes-v1.15.3:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.3-beta.0:build :kuberig-dsl-kubernetes-v1.15.3-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.4:build :kuberig-dsl-kubernetes-v1.15.4:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.4-beta.0:build :kuberig-dsl-kubernetes-v1.15.4-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.5:build :kuberig-dsl-kubernetes-v1.15.5:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.5-beta.0:build :kuberig-dsl-kubernetes-v1.15.5-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.6:build :kuberig-dsl-kubernetes-v1.15.6:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.6-beta.0:build :kuberig-dsl-kubernetes-v1.15.6-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.7:build :kuberig-dsl-kubernetes-v1.15.7:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.7-beta.0:build :kuberig-dsl-kubernetes-v1.15.7-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.8:build :kuberig-dsl-kubernetes-v1.15.8:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.8-beta.0:build :kuberig-dsl-kubernetes-v1.15.8-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.8-beta.1:build :kuberig-dsl-kubernetes-v1.15.8-beta.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.9:build :kuberig-dsl-kubernetes-v1.15.9:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.9-beta.0:build :kuberig-dsl-kubernetes-v1.15.9-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.10:build :kuberig-dsl-kubernetes-v1.15.10:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.10-beta.0:build :kuberig-dsl-kubernetes-v1.15.10-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.15.11-beta.0:build :kuberig-dsl-kubernetes-v1.15.11-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.16.0:build :kuberig-dsl-kubernetes-v1.16.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.16.0-alpha.0:build :kuberig-dsl-kubernetes-v1.16.0-alpha.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.16.0-alpha.1:build :kuberig-dsl-kubernetes-v1.16.0-alpha.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.16.0-alpha.2:build :kuberig-dsl-kubernetes-v1.16.0-alpha.2:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.16.0-alpha.3:build :kuberig-dsl-kubernetes-v1.16.0-alpha.3:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.16.0-beta.0:build :kuberig-dsl-kubernetes-v1.16.0-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.16.0-beta.1:build :kuberig-dsl-kubernetes-v1.16.0-beta.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.16.0-beta.2:build :kuberig-dsl-kubernetes-v1.16.0-beta.2:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.16.0-rc.1:build :kuberig-dsl-kubernetes-v1.16.0-rc.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.16.0-rc.2:build :kuberig-dsl-kubernetes-v1.16.0-rc.2:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.16.1:build :kuberig-dsl-kubernetes-v1.16.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.16.1-beta.0:build :kuberig-dsl-kubernetes-v1.16.1-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.16.2:build :kuberig-dsl-kubernetes-v1.16.2:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.16.2-beta.0:build :kuberig-dsl-kubernetes-v1.16.2-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.16.3:build :kuberig-dsl-kubernetes-v1.16.3:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.16.3-beta.0:build :kuberig-dsl-kubernetes-v1.16.3-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.16.4:build :kuberig-dsl-kubernetes-v1.16.4:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.16.4-beta.0:build :kuberig-dsl-kubernetes-v1.16.4-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.16.5:build :kuberig-dsl-kubernetes-v1.16.5:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.16.5-beta.0:build :kuberig-dsl-kubernetes-v1.16.5-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.16.5-beta.1:build :kuberig-dsl-kubernetes-v1.16.5-beta.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.16.6:build :kuberig-dsl-kubernetes-v1.16.6:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.16.6-beta.0:build :kuberig-dsl-kubernetes-v1.16.6-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.16.7:build :kuberig-dsl-kubernetes-v1.16.7:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.16.7-beta.0:build :kuberig-dsl-kubernetes-v1.16.7-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.16.8-beta.0:build :kuberig-dsl-kubernetes-v1.16.8-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.17.0:build :kuberig-dsl-kubernetes-v1.17.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.17.0-alpha.0:build :kuberig-dsl-kubernetes-v1.17.0-alpha.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.17.0-alpha.1:build :kuberig-dsl-kubernetes-v1.17.0-alpha.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.17.0-alpha.2:build :kuberig-dsl-kubernetes-v1.17.0-alpha.2:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.17.0-alpha.3:build :kuberig-dsl-kubernetes-v1.17.0-alpha.3:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.17.0-beta.0:build :kuberig-dsl-kubernetes-v1.17.0-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.17.0-beta.1:build :kuberig-dsl-kubernetes-v1.17.0-beta.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.17.0-beta.2:build :kuberig-dsl-kubernetes-v1.17.0-beta.2:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.17.0-rc.1:build :kuberig-dsl-kubernetes-v1.17.0-rc.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.17.0-rc.2:build :kuberig-dsl-kubernetes-v1.17.0-rc.2:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.17.1:build :kuberig-dsl-kubernetes-v1.17.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.17.1-beta.0:build :kuberig-dsl-kubernetes-v1.17.1-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.17.2:build :kuberig-dsl-kubernetes-v1.17.2:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.17.2-beta.0:build :kuberig-dsl-kubernetes-v1.17.2-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.17.3:build :kuberig-dsl-kubernetes-v1.17.3:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.17.3-beta.0:build :kuberig-dsl-kubernetes-v1.17.3-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.17.4-beta.0:build :kuberig-dsl-kubernetes-v1.17.4-beta.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.18.0-alpha.0:build :kuberig-dsl-kubernetes-v1.18.0-alpha.0:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.18.0-alpha.1:build :kuberig-dsl-kubernetes-v1.18.0-alpha.1:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.18.0-alpha.2:build :kuberig-dsl-kubernetes-v1.18.0-alpha.2:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.18.0-alpha.3:build :kuberig-dsl-kubernetes-v1.18.0-alpha.3:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.18.0-alpha.4:build :kuberig-dsl-kubernetes-v1.18.0-alpha.4:bintrayUpload
./gradlew :kuberig-dsl-kubernetes-v1.18.0-alpha.5:build :kuberig-dsl-kubernetes-v1.18.0-alpha.5:bintrayUpload