# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

workflows:
  upstream-and-availability-sync:
    triggers:
      - schedule:
          # https://crontab.guru/#0_0-23_*_*_*
          # every hour
          cron: "0 0-23 * * *"
          filters:
            branches:
              only:
                - circleci-project-setup
    jobs:
      - upstream-and-availability-sync:
          context: kuberig-context

jobs:
  upstream-and-availability-sync:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - add_ssh_keys:
          fingerprints:
            - "d1:87:82:6c:c1:de:05:3e:e7:51:ec:34:3b:eb:a1:fd"
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}
      # detect upstream versions and publish them to bintray
      - run: |
          gradle generateDslProjects publishMissing showMissingFromJCenter
          git add --all
          git config user.name "circleci"
          git config user.email "circleci@rigel.dev"
          changed_files=$(git status --porcelain --untracked-files=no | wc -l)
          [ $changed_files -gt 0 ] && git commit -m "upstream sync" && git push origin master